`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: Nov  1 2023 15:54:09 CST (Nov  1 2023 07:54:09 UTC)

module SysPE_Not_1U_1U_1(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  CLKINVX12 g2(.A (in1), .Y (out1));
endmodule


