`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: Nov  1 2023 15:54:08 CST (Nov  1 2023 07:54:08 UTC)

module SysPE_Mul_8Ux8U_16U_1(in2, in1, out1);
  input [7:0] in2, in1;
  output [15:0] out1;
  wire [7:0] in2, in1;
  wire [15:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_4, mul_22_8_n_6,
       mul_22_8_n_7, mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_11;
  wire mul_22_8_n_12, mul_22_8_n_14, mul_22_8_n_18, mul_22_8_n_19,
       mul_22_8_n_20, mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23;
  wire mul_22_8_n_24, mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27,
       mul_22_8_n_28, mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_33;
  wire mul_22_8_n_35, mul_22_8_n_36, mul_22_8_n_37, mul_22_8_n_38,
       mul_22_8_n_39, mul_22_8_n_40, mul_22_8_n_41, mul_22_8_n_42;
  wire mul_22_8_n_43, mul_22_8_n_44, mul_22_8_n_45, mul_22_8_n_46,
       mul_22_8_n_47, mul_22_8_n_48, mul_22_8_n_49, mul_22_8_n_50;
  wire mul_22_8_n_51, mul_22_8_n_52, mul_22_8_n_53, mul_22_8_n_54,
       mul_22_8_n_55, mul_22_8_n_56, mul_22_8_n_57, mul_22_8_n_58;
  wire mul_22_8_n_59, mul_22_8_n_60, mul_22_8_n_61, mul_22_8_n_62,
       mul_22_8_n_63, mul_22_8_n_64, mul_22_8_n_65, mul_22_8_n_66;
  wire mul_22_8_n_67, mul_22_8_n_68, mul_22_8_n_69, mul_22_8_n_70,
       mul_22_8_n_71, mul_22_8_n_72, mul_22_8_n_74, mul_22_8_n_75;
  wire mul_22_8_n_76, mul_22_8_n_77, mul_22_8_n_78, mul_22_8_n_79,
       mul_22_8_n_80, mul_22_8_n_81, mul_22_8_n_82, mul_22_8_n_83;
  wire mul_22_8_n_84, mul_22_8_n_85, mul_22_8_n_86, mul_22_8_n_87,
       mul_22_8_n_88, mul_22_8_n_89, mul_22_8_n_90, mul_22_8_n_91;
  wire mul_22_8_n_92, mul_22_8_n_93, mul_22_8_n_94, mul_22_8_n_95,
       mul_22_8_n_96, mul_22_8_n_97, mul_22_8_n_98, mul_22_8_n_99;
  wire mul_22_8_n_100, mul_22_8_n_101, mul_22_8_n_102, mul_22_8_n_103,
       mul_22_8_n_104, mul_22_8_n_105, mul_22_8_n_106, mul_22_8_n_107;
  wire mul_22_8_n_108, mul_22_8_n_109, mul_22_8_n_110, mul_22_8_n_111,
       mul_22_8_n_112, mul_22_8_n_114, mul_22_8_n_115, mul_22_8_n_116;
  wire mul_22_8_n_117, mul_22_8_n_118, mul_22_8_n_119, mul_22_8_n_121,
       mul_22_8_n_122, mul_22_8_n_123, mul_22_8_n_124, mul_22_8_n_125;
  wire mul_22_8_n_126, mul_22_8_n_128, mul_22_8_n_129, mul_22_8_n_130,
       mul_22_8_n_131, mul_22_8_n_132, mul_22_8_n_133, mul_22_8_n_134;
  wire mul_22_8_n_135, mul_22_8_n_136, mul_22_8_n_137, mul_22_8_n_138,
       mul_22_8_n_139, mul_22_8_n_140, mul_22_8_n_141, mul_22_8_n_142;
  wire mul_22_8_n_143, mul_22_8_n_144, mul_22_8_n_145, mul_22_8_n_146,
       mul_22_8_n_147, mul_22_8_n_148, mul_22_8_n_149, mul_22_8_n_150;
  wire mul_22_8_n_151, mul_22_8_n_153, mul_22_8_n_154, mul_22_8_n_155,
       mul_22_8_n_156, mul_22_8_n_157, mul_22_8_n_158, mul_22_8_n_159;
  wire mul_22_8_n_160, mul_22_8_n_161, mul_22_8_n_162, mul_22_8_n_163,
       mul_22_8_n_164, mul_22_8_n_165, mul_22_8_n_166, mul_22_8_n_167;
  wire mul_22_8_n_168, mul_22_8_n_169, mul_22_8_n_170, mul_22_8_n_171,
       mul_22_8_n_172, mul_22_8_n_173, mul_22_8_n_174, mul_22_8_n_175;
  wire mul_22_8_n_176, mul_22_8_n_177, mul_22_8_n_178, mul_22_8_n_179,
       mul_22_8_n_180, mul_22_8_n_181, mul_22_8_n_182, mul_22_8_n_183;
  wire mul_22_8_n_184, mul_22_8_n_185, mul_22_8_n_186, mul_22_8_n_189,
       mul_22_8_n_190, mul_22_8_n_193, mul_22_8_n_194, mul_22_8_n_195;
  wire mul_22_8_n_196, mul_22_8_n_197, mul_22_8_n_198, mul_22_8_n_199,
       mul_22_8_n_200, mul_22_8_n_201, mul_22_8_n_202, mul_22_8_n_203;
  wire mul_22_8_n_204, mul_22_8_n_205, mul_22_8_n_206, mul_22_8_n_207,
       mul_22_8_n_208, mul_22_8_n_209, mul_22_8_n_210, mul_22_8_n_211;
  wire mul_22_8_n_212, mul_22_8_n_213, mul_22_8_n_214, mul_22_8_n_215,
       mul_22_8_n_216, mul_22_8_n_217, mul_22_8_n_218, mul_22_8_n_219;
  wire mul_22_8_n_220, mul_22_8_n_221, mul_22_8_n_222, mul_22_8_n_223,
       mul_22_8_n_224, mul_22_8_n_225, mul_22_8_n_226, mul_22_8_n_227;
  wire mul_22_8_n_228, mul_22_8_n_229, mul_22_8_n_230, mul_22_8_n_231,
       mul_22_8_n_232, mul_22_8_n_233, mul_22_8_n_234, mul_22_8_n_235;
  wire mul_22_8_n_236, mul_22_8_n_237, mul_22_8_n_238, mul_22_8_n_239,
       mul_22_8_n_240, mul_22_8_n_241, mul_22_8_n_242, mul_22_8_n_243;
  wire mul_22_8_n_244, mul_22_8_n_245, mul_22_8_n_246, mul_22_8_n_247,
       mul_22_8_n_248, mul_22_8_n_249, mul_22_8_n_250, mul_22_8_n_251;
  wire mul_22_8_n_252, mul_22_8_n_253, mul_22_8_n_254, mul_22_8_n_255,
       mul_22_8_n_256, mul_22_8_n_257, mul_22_8_n_258, mul_22_8_n_259;
  wire mul_22_8_n_260, mul_22_8_n_261, mul_22_8_n_262, n_287, n_289,
       n_291, n_292, n_294;
  wire n_301, n_303, n_304, n_305, n_316, n_327, n_328, n_329;
  wire n_331, n_332, n_333, n_335, n_336, n_337, n_338, n_339;
  wire n_341, n_342, n_343, n_344, n_346, n_347, n_349, n_350;
  wire n_351, n_352;
  ADDFX1 mul_22_8_cdnfadd_003_0(.A (mul_22_8_n_57), .B (mul_22_8_n_74),
       .CI (mul_22_8_n_116), .CO (mul_22_8_n_253), .S (mul_22_8_n_241));
  ADDFX1 mul_22_8_cdnfadd_004_0(.A (mul_22_8_n_89), .B (mul_22_8_n_52),
       .CI (mul_22_8_n_80), .CO (mul_22_8_n_239), .S (mul_22_8_n_240));
  ADDFXL mul_22_8_cdnfadd_004_1(.A (mul_22_8_n_112), .B
       (mul_22_8_n_101), .CI (mul_22_8_n_240), .CO (mul_22_8_n_254), .S
       (mul_22_8_n_242));
  ADDFX1 mul_22_8_cdnfadd_005_0(.A (mul_22_8_n_51), .B (mul_22_8_n_55),
       .CI (mul_22_8_n_48), .CO (mul_22_8_n_236), .S (mul_22_8_n_238));
  ADDFX1 mul_22_8_cdnfadd_005_1(.A (mul_22_8_n_84), .B
       (mul_22_8_n_118), .CI (mul_22_8_n_105), .CO (mul_22_8_n_234), .S
       (mul_22_8_n_237));
  ADDFHXL mul_22_8_cdnfadd_005_2(.A (mul_22_8_n_239), .B
       (mul_22_8_n_238), .CI (mul_22_8_n_237), .CO (mul_22_8_n_255), .S
       (mul_22_8_n_243));
  ADDFXL mul_22_8_cdnfadd_006_0(.A (mul_22_8_n_77), .B (mul_22_8_n_53),
       .CI (mul_22_8_n_39), .CO (mul_22_8_n_231), .S (mul_22_8_n_235));
  ADDFX1 mul_22_8_cdnfadd_006_1(.A (mul_22_8_n_59), .B (mul_22_8_n_82),
       .CI (mul_22_8_n_104), .CO (mul_22_8_n_228), .S (mul_22_8_n_233));
  ADDFXL mul_22_8_cdnfadd_006_2(.A (mul_22_8_n_117), .B
       (mul_22_8_n_236), .CI (mul_22_8_n_235), .CO (mul_22_8_n_226), .S
       (mul_22_8_n_232));
  ADDFX1 mul_22_8_cdnfadd_006_3(.A (mul_22_8_n_234), .B
       (mul_22_8_n_233), .CI (mul_22_8_n_232), .CO (mul_22_8_n_256), .S
       (mul_22_8_n_244));
  ADDFHXL mul_22_8_cdnfadd_007_0(.A (mul_22_8_n_78), .B
       (mul_22_8_n_69), .CI (mul_22_8_n_50), .CO (mul_22_8_n_224), .S
       (mul_22_8_n_229));
  ADDFXL mul_22_8_cdnfadd_007_1(.A (mul_22_8_n_40), .B (mul_22_8_n_36),
       .CI (mul_22_8_n_87), .CO (mul_22_8_n_223), .S (mul_22_8_n_230));
  ADDFX1 mul_22_8_cdnfadd_007_2(.A (mul_22_8_n_110), .B
       (mul_22_8_n_114), .CI (mul_22_8_n_231), .CO (mul_22_8_n_220), .S
       (mul_22_8_n_227));
  ADDFX1 mul_22_8_cdnfadd_007_3(.A (mul_22_8_n_230), .B
       (mul_22_8_n_229), .CI (mul_22_8_n_228), .CO (mul_22_8_n_218), .S
       (mul_22_8_n_225));
  ADDFHXL mul_22_8_cdnfadd_007_4(.A (mul_22_8_n_227), .B
       (mul_22_8_n_226), .CI (mul_22_8_n_225), .CO (mul_22_8_n_257), .S
       (mul_22_8_n_245));
  ADDFX1 mul_22_8_cdnfadd_008_0(.A (mul_22_8_n_54), .B (mul_22_8_n_56),
       .CI (mul_22_8_n_45), .CO (mul_22_8_n_216), .S (mul_22_8_n_222));
  ADDFHXL mul_22_8_cdnfadd_008_1(.A (mul_22_8_n_81), .B
       (mul_22_8_n_83), .CI (mul_22_8_n_111), .CO (mul_22_8_n_213), .S
       (mul_22_8_n_221));
  ADDFX1 mul_22_8_cdnfadd_008_2(.A (mul_22_8_n_102), .B
       (mul_22_8_n_224), .CI (mul_22_8_n_223), .CO (mul_22_8_n_212), .S
       (mul_22_8_n_219));
  ADDFHXL mul_22_8_cdnfadd_008_3(.A (mul_22_8_n_222), .B
       (mul_22_8_n_221), .CI (mul_22_8_n_220), .CO (mul_22_8_n_209), .S
       (mul_22_8_n_217));
  ADDFHXL mul_22_8_cdnfadd_008_4(.A (mul_22_8_n_219), .B
       (mul_22_8_n_218), .CI (mul_22_8_n_217), .CO (mul_22_8_n_258), .S
       (mul_22_8_n_246));
  ADDFX1 mul_22_8_cdnfadd_009_0(.A (mul_22_8_n_76), .B (mul_22_8_n_58),
       .CI (mul_22_8_n_37), .CO (mul_22_8_n_207), .S (mul_22_8_n_214));
  ADDFHX1 mul_22_8_cdnfadd_009_1(.A (mul_22_8_n_90), .B
       (mul_22_8_n_71), .CI (mul_22_8_n_86), .CO (mul_22_8_n_208), .S
       (mul_22_8_n_215));
  ADDFX1 mul_22_8_cdnfadd_009_2(.A (n_301), .B (mul_22_8_n_216), .CI
       (mul_22_8_n_215), .CO (mul_22_8_n_204), .S (mul_22_8_n_211));
  ADDFHXL mul_22_8_cdnfadd_009_3(.A (mul_22_8_n_214), .B
       (mul_22_8_n_213), .CI (mul_22_8_n_212), .CO (mul_22_8_n_202), .S
       (mul_22_8_n_210));
  ADDFHXL mul_22_8_cdnfadd_009_4(.A (mul_22_8_n_211), .B
       (mul_22_8_n_210), .CI (mul_22_8_n_209), .CO (mul_22_8_n_259), .S
       (mul_22_8_n_247));
  ADDFX1 mul_22_8_cdnfadd_010_0(.A (mul_22_8_n_44), .B (mul_22_8_n_49),
       .CI (mul_22_8_n_43), .CO (mul_22_8_n_201), .S (mul_22_8_n_206));
  ADDFHXL mul_22_8_cdnfadd_010_1(.A (mul_22_8_n_79), .B
       (mul_22_8_n_38), .CI (mul_22_8_n_208), .CO (mul_22_8_n_199), .S
       (mul_22_8_n_205));
  ADDFHXL mul_22_8_cdnfadd_010_2(.A (mul_22_8_n_207), .B
       (mul_22_8_n_206), .CI (mul_22_8_n_205), .CO (mul_22_8_n_197), .S
       (mul_22_8_n_203));
  ADDFHXL mul_22_8_cdnfadd_010_3(.A (mul_22_8_n_204), .B
       (mul_22_8_n_203), .CI (mul_22_8_n_202), .CO (mul_22_8_n_260), .S
       (mul_22_8_n_248));
  ADDFX1 mul_22_8_cdnfadd_011_0(.A (mul_22_8_n_46), .B (mul_22_8_n_72),
       .CI (mul_22_8_n_42), .CO (mul_22_8_n_196), .S (mul_22_8_n_200));
  ADDFHXL mul_22_8_cdnfadd_011_1(.A (mul_22_8_n_41), .B
       (mul_22_8_n_201), .CI (mul_22_8_n_200), .CO (mul_22_8_n_194), .S
       (mul_22_8_n_198));
  ADDFHXL mul_22_8_cdnfadd_011_2(.A (mul_22_8_n_199), .B
       (mul_22_8_n_198), .CI (mul_22_8_n_197), .CO (mul_22_8_n_250), .S
       (mul_22_8_n_249));
  ADDFX1 mul_22_8_cdnfadd_012_0(.A (mul_22_8_n_47), .B (mul_22_8_n_70),
       .CI (mul_22_8_n_88), .CO (mul_22_8_n_193), .S (mul_22_8_n_195));
  ADDFX1 mul_22_8_cdnfadd_012_1(.A (mul_22_8_n_196), .B
       (mul_22_8_n_195), .CI (mul_22_8_n_194), .CO (mul_22_8_n_251), .S
       (mul_22_8_n_261));
  ADDFX1 mul_22_8_cdnfadd_013_0(.A (mul_22_8_n_75), .B (mul_22_8_n_85),
       .CI (mul_22_8_n_193), .CO (mul_22_8_n_252), .S (mul_22_8_n_262));
  MXI2XL mul_22_8_g1186(.A (mul_22_8_n_130), .B (mul_22_8_n_131), .S0
       (mul_22_8_n_190), .Y (out1[14]));
  MXI2XL mul_22_8_g1187(.A (mul_22_8_n_144), .B (mul_22_8_n_143), .S0
       (mul_22_8_n_189), .Y (out1[13]));
  NOR2X1 mul_22_8_g1188(.A (mul_22_8_n_174), .B (mul_22_8_n_186), .Y
       (mul_22_8_n_190));
  AOI2BB1XL mul_22_8_g1189(.A0N (mul_22_8_n_163), .A1N (mul_22_8_n_18),
       .B0 (mul_22_8_n_157), .Y (mul_22_8_n_189));
  MXI2XL mul_22_8_g1191(.A (mul_22_8_n_165), .B (mul_22_8_n_166), .S0
       (mul_22_8_n_184), .Y (out1[11]));
  NAND2X1 mul_22_8_g1192(.A (mul_22_8_n_185), .B (mul_22_8_n_183), .Y
       (out1[15]));
  NOR2X1 mul_22_8_g1193(.A (mul_22_8_n_169), .B (mul_22_8_n_18), .Y
       (mul_22_8_n_186));
  AOI21X1 mul_22_8_g1194(.A0 (mul_22_8_n_178), .A1 (n_294), .B0
       (mul_22_8_n_180), .Y (mul_22_8_n_185));
  NOR2X1 mul_22_8_g1197(.A (mul_22_8_n_9), .B (mul_22_8_n_182), .Y
       (mul_22_8_n_184));
  AOI21X1 mul_22_8_g1198(.A0 (mul_22_8_n_178), .A1 (n_287), .B0
       (mul_22_8_n_125), .Y (mul_22_8_n_183));
  NOR2X1 mul_22_8_g1200(.A (n_327), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_182));
  NAND2X2 mul_22_8_g1202(.A (mul_22_8_n_173), .B (mul_22_8_n_179), .Y
       (mul_22_8_n_181));
  AND2XL mul_22_8_g1203(.A (mul_22_8_n_126), .B (mul_22_8_n_174), .Y
       (mul_22_8_n_180));
  NAND2X1 mul_22_8_g1206(.A (mul_22_8_n_171), .B (mul_22_8_n_176), .Y
       (mul_22_8_n_179));
  NOR2BX1 mul_22_8_g1209(.AN (mul_22_8_n_126), .B (mul_22_8_n_169), .Y
       (mul_22_8_n_178));
  NAND2X1 mul_22_8_g1211(.A (mul_22_8_n_168), .B (mul_22_8_n_171), .Y
       (mul_22_8_n_177));
  OAI21X2 mul_22_8_g1212(.A0 (mul_22_8_n_160), .A1 (mul_22_8_n_161),
       .B0 (mul_22_8_n_164), .Y (mul_22_8_n_176));
  NOR2BX1 mul_22_8_g1213(.AN (mul_22_8_n_161), .B (mul_22_8_n_172), .Y
       (mul_22_8_n_175));
  OAI2BB1X1 mul_22_8_g1214(.A0N (mul_22_8_n_157), .A1N
       (mul_22_8_n_142), .B0 (mul_22_8_n_141), .Y (mul_22_8_n_174));
  AOI31X1 mul_22_8_g1215(.A0 (mul_22_8_n_158), .A1 (mul_22_8_n_259),
       .A2 (mul_22_8_n_248), .B0 (mul_22_8_n_159), .Y (mul_22_8_n_173));
  NOR2X1 mul_22_8_g1216(.A (mul_22_8_n_156), .B (n_304), .Y
       (mul_22_8_n_172));
  NOR2BX1 mul_22_8_g1217(.AN (mul_22_8_n_158), .B (mul_22_8_n_162), .Y
       (mul_22_8_n_171));
  NOR2X1 mul_22_8_g1219(.A (mul_22_8_n_9), .B (n_328), .Y
       (mul_22_8_n_170));
  NAND2BX1 mul_22_8_g1224(.AN (mul_22_8_n_163), .B (mul_22_8_n_142), .Y
       (mul_22_8_n_169));
  NOR2X1 mul_22_8_g1226(.A (mul_22_8_n_156), .B (mul_22_8_n_160), .Y
       (mul_22_8_n_168));
  NOR2X1 mul_22_8_g1228(.A (mul_22_8_n_157), .B (mul_22_8_n_163), .Y
       (mul_22_8_n_167));
  INVX1 mul_22_8_g1229(.A (mul_22_8_n_165), .Y (mul_22_8_n_166));
  NOR2BX1 mul_22_8_g1230(.AN (mul_22_8_n_158), .B (mul_22_8_n_159), .Y
       (mul_22_8_n_165));
  NAND2X1 mul_22_8_g1233(.A (mul_22_8_n_258), .B (mul_22_8_n_247), .Y
       (mul_22_8_n_164));
  NOR2X1 mul_22_8_g1234(.A (mul_22_8_n_250), .B (mul_22_8_n_261), .Y
       (mul_22_8_n_163));
  NOR2X2 mul_22_8_g1235(.A (mul_22_8_n_259), .B (mul_22_8_n_248), .Y
       (mul_22_8_n_162));
  NAND2X1 mul_22_8_g1236(.A (mul_22_8_n_257), .B (mul_22_8_n_246), .Y
       (mul_22_8_n_161));
  NOR2X2 mul_22_8_g1237(.A (mul_22_8_n_258), .B (mul_22_8_n_247), .Y
       (mul_22_8_n_160));
  NOR2X1 mul_22_8_g1239(.A (n_291), .B (mul_22_8_n_153), .Y
       (mul_22_8_n_159));
  NAND2X1 mul_22_8_g1240(.A (mul_22_8_n_153), .B (n_292), .Y
       (mul_22_8_n_158));
  AND2X1 mul_22_8_g1241(.A (mul_22_8_n_250), .B (mul_22_8_n_261), .Y
       (mul_22_8_n_157));
  NOR2X1 mul_22_8_g1243(.A (mul_22_8_n_257), .B (mul_22_8_n_246), .Y
       (mul_22_8_n_156));
  NOR2X2 mul_22_8_g1244(.A (mul_22_8_n_154), .B (mul_22_8_n_151), .Y
       (mul_22_8_n_155));
  OAI31X1 mul_22_8_g1246(.A0 (mul_22_8_n_135), .A1 (mul_22_8_n_139),
       .A2 (mul_22_8_n_146), .B0 (mul_22_8_n_147), .Y (mul_22_8_n_154));
  INVX1 mul_22_8_g1247(.A (mul_22_8_n_249), .Y (mul_22_8_n_153));
  NAND2X2 mul_22_8_g1251(.A (mul_22_8_n_149), .B (mul_22_8_n_150), .Y
       (mul_22_8_n_151));
  NAND2BX1 mul_22_8_g1252(.AN (mul_22_8_n_137), .B (mul_22_8_n_148), .Y
       (mul_22_8_n_150));
  OR2X1 mul_22_8_g1255(.A (mul_22_8_n_140), .B (mul_22_8_n_146), .Y
       (mul_22_8_n_149));
  NOR2X1 mul_22_8_g1256(.A (mul_22_8_n_139), .B (mul_22_8_n_146), .Y
       (mul_22_8_n_148));
  NAND2X1 mul_22_8_g1258(.A (mul_22_8_n_256), .B (mul_22_8_n_245), .Y
       (mul_22_8_n_147));
  NOR2X2 mul_22_8_g1259(.A (mul_22_8_n_256), .B (mul_22_8_n_245), .Y
       (mul_22_8_n_146));
  OAI21X1 mul_22_8_g1261(.A0 (mul_22_8_n_139), .A1 (mul_22_8_n_4), .B0
       (mul_22_8_n_140), .Y (mul_22_8_n_145));
  INVX1 mul_22_8_g1263(.A (mul_22_8_n_143), .Y (mul_22_8_n_144));
  NAND2X1 mul_22_8_g1264(.A (mul_22_8_n_141), .B (mul_22_8_n_142), .Y
       (mul_22_8_n_143));
  NAND2X1 mul_22_8_g1265(.A (mul_22_8_n_138), .B (mul_22_8_n_122), .Y
       (mul_22_8_n_142));
  OR2X1 mul_22_8_g1266(.A (mul_22_8_n_138), .B (mul_22_8_n_122), .Y
       (mul_22_8_n_141));
  NAND2X1 mul_22_8_g1267(.A (mul_22_8_n_255), .B (mul_22_8_n_244), .Y
       (mul_22_8_n_140));
  NOR2X2 mul_22_8_g1269(.A (mul_22_8_n_255), .B (mul_22_8_n_244), .Y
       (mul_22_8_n_139));
  INVX1 mul_22_8_g1273(.A (mul_22_8_n_251), .Y (mul_22_8_n_138));
  NOR2X2 mul_22_8_g1275(.A (mul_22_8_n_134), .B (mul_22_8_n_1), .Y
       (mul_22_8_n_137));
  NOR2X1 mul_22_8_g1277(.A (mul_22_8_n_134), .B (mul_22_8_n_133), .Y
       (mul_22_8_n_136));
  OAI21X1 mul_22_8_g1278(.A0 (mul_22_8_n_254), .A1 (mul_22_8_n_243),
       .B0 (mul_22_8_n_20), .Y (mul_22_8_n_135));
  CLKAND2X2 mul_22_8_g1279(.A (mul_22_8_n_254), .B (mul_22_8_n_243), .Y
       (mul_22_8_n_134));
  NOR2X1 mul_22_8_g1280(.A (mul_22_8_n_254), .B (mul_22_8_n_243), .Y
       (mul_22_8_n_133));
  NOR2X1 mul_22_8_g1283(.A (mul_22_8_n_0), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_132));
  INVXL mul_22_8_g1286(.A (mul_22_8_n_130), .Y (mul_22_8_n_131));
  NOR2BX1 mul_22_8_g1287(.AN (mul_22_8_n_126), .B (mul_22_8_n_125), .Y
       (mul_22_8_n_130));
  NOR2X1 mul_22_8_g1288(.A (mul_22_8_n_0), .B (mul_22_8_n_124), .Y
       (mul_22_8_n_129));
  ADDFX1 mul_22_8_g1290(.A (mul_22_8_n_119), .B (mul_22_8_n_109), .CI
       (mul_22_8_n_241), .CO (mul_22_8_n_128), .S (out1[3]));
  NAND2X1 mul_22_8_g1291(.A (mul_22_8_n_123), .B (mul_22_8_n_64), .Y
       (mul_22_8_n_126));
  NOR2X1 mul_22_8_g1292(.A (mul_22_8_n_123), .B (mul_22_8_n_64), .Y
       (mul_22_8_n_125));
  NOR2BX1 mul_22_8_g1295(.AN (mul_22_8_n_121), .B (mul_22_8_n_242), .Y
       (mul_22_8_n_124));
  INVX1 mul_22_8_g1296(.A (mul_22_8_n_252), .Y (mul_22_8_n_123));
  INVX1 mul_22_8_g1298(.A (mul_22_8_n_262), .Y (mul_22_8_n_122));
  INVX1 mul_22_8_g1299(.A (mul_22_8_n_253), .Y (mul_22_8_n_121));
  ADDFX1 mul_22_8_g1300(.A (mul_22_8_n_108), .B (mul_22_8_n_68), .CI
       (mul_22_8_n_115), .CO (mul_22_8_n_119), .S (out1[2]));
  NOR2BX1 mul_22_8_g1301(.AN (mul_22_8_n_107), .B (mul_22_8_n_104), .Y
       (mul_22_8_n_118));
  AOI21X1 mul_22_8_g1302(.A0 (mul_22_8_n_95), .A1 (mul_22_8_n_96), .B0
       (mul_22_8_n_110), .Y (mul_22_8_n_117));
  NOR2BX1 mul_22_8_g1303(.AN (mul_22_8_n_106), .B (mul_22_8_n_101), .Y
       (mul_22_8_n_116));
  AOI21X1 mul_22_8_g1304(.A0 (mul_22_8_n_93), .A1 (mul_22_8_n_99), .B0
       (mul_22_8_n_109), .Y (mul_22_8_n_115));
  AOI21X1 mul_22_8_g1305(.A0 (mul_22_8_n_94), .A1 (mul_22_8_n_60), .B0
       (mul_22_8_n_102), .Y (mul_22_8_n_114));
  AOI21X1 mul_22_8_g1306(.A0 (mul_22_8_n_98), .A1 (mul_22_8_n_92), .B0
       (mul_22_8_n_108), .Y (out1[1]));
  AOI21X1 mul_22_8_g1307(.A0 (mul_22_8_n_66), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_105), .Y (mul_22_8_n_112));
  NOR2BX1 mul_22_8_g1308(.AN (mul_22_8_n_100), .B (mul_22_8_n_103), .Y
       (mul_22_8_n_111));
  NAND2X1 mul_22_8_g1309(.A (mul_22_8_n_61), .B (mul_22_8_n_62), .Y
       (mul_22_8_n_107));
  NAND2X1 mul_22_8_g1310(.A (mul_22_8_n_97), .B (mul_22_8_n_63), .Y
       (mul_22_8_n_106));
  NOR2X1 mul_22_8_g1311(.A (mul_22_8_n_95), .B (mul_22_8_n_96), .Y
       (mul_22_8_n_110));
  NOR2X1 mul_22_8_g1312(.A (mul_22_8_n_93), .B (mul_22_8_n_99), .Y
       (mul_22_8_n_109));
  NOR2X1 mul_22_8_g1313(.A (mul_22_8_n_98), .B (mul_22_8_n_92), .Y
       (mul_22_8_n_108));
  NAND2X1 mul_22_8_g1314(.A (mul_22_8_n_91), .B (mul_22_8_n_67), .Y
       (mul_22_8_n_100));
  NOR2X1 mul_22_8_g1315(.A (mul_22_8_n_66), .B (mul_22_8_n_65), .Y
       (mul_22_8_n_105));
  NOR2X1 mul_22_8_g1316(.A (mul_22_8_n_61), .B (mul_22_8_n_62), .Y
       (mul_22_8_n_104));
  NOR2X2 mul_22_8_g1317(.A (mul_22_8_n_91), .B (mul_22_8_n_67), .Y
       (mul_22_8_n_103));
  NOR2X1 mul_22_8_g1318(.A (mul_22_8_n_94), .B (mul_22_8_n_60), .Y
       (mul_22_8_n_102));
  NOR2X1 mul_22_8_g1319(.A (mul_22_8_n_97), .B (mul_22_8_n_63), .Y
       (mul_22_8_n_101));
  NOR2X6 mul_22_8_g1320(.A (n_337), .B (mul_22_8_n_30), .Y
       (mul_22_8_n_90));
  NOR2X1 mul_22_8_g1321(.A (mul_22_8_n_22), .B (n_351), .Y
       (mul_22_8_n_89));
  AND2XL mul_22_8_g1322(.A (in1[5]), .B (in2[7]), .Y (mul_22_8_n_88));
  NOR2X1 mul_22_8_g1323(.A (mul_22_8_n_22), .B (mul_22_8_n_30), .Y
       (mul_22_8_n_87));
  NOR2X2 mul_22_8_g1324(.A (mul_22_8_n_33), .B (mul_22_8_n_29), .Y
       (mul_22_8_n_86));
  AND2XL mul_22_8_g1325(.A (in1[6]), .B (in2[7]), .Y (mul_22_8_n_85));
  AND2XL mul_22_8_g1326(.A (in1[0]), .B (in2[5]), .Y (mul_22_8_n_84));
  AND2XL mul_22_8_g1327(.A (in1[1]), .B (in2[7]), .Y (mul_22_8_n_83));
  AND2XL mul_22_8_g1328(.A (in1[0]), .B (in2[6]), .Y (mul_22_8_n_82));
  AND2XL mul_22_8_g1329(.A (in1[2]), .B (in2[6]), .Y (mul_22_8_n_81));
  NOR2X1 mul_22_8_g1330(.A (mul_22_8_n_33), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_80));
  AND2X1 mul_22_8_g1331(.A (n_342), .B (in2[7]), .Y (mul_22_8_n_79));
  NOR2X2 mul_22_8_g1332(.A (n_336), .B (n_346), .Y (mul_22_8_n_78));
  NOR2X1 mul_22_8_g1333(.A (n_344), .B (n_347), .Y (mul_22_8_n_77));
  NOR2X1 mul_22_8_g1334(.A (mul_22_8_n_23), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_76));
  AND2XL mul_22_8_g1335(.A (in1[7]), .B (in2[6]), .Y (mul_22_8_n_75));
  AND2XL mul_22_8_g1336(.A (in1[1]), .B (in2[2]), .Y (mul_22_8_n_74));
  AND2XL mul_22_8_g1337(.A (in1[0]), .B (in2[0]), .Y (out1[0]));
  NOR2X1 mul_22_8_g1338(.A (mul_22_8_n_25), .B (mul_22_8_n_21), .Y
       (mul_22_8_n_72));
  NOR2X6 mul_22_8_g1339(.A (mul_22_8_n_35), .B (mul_22_8_n_27), .Y
       (mul_22_8_n_71));
  AND2XL mul_22_8_g1340(.A (in1[6]), .B (in2[6]), .Y (mul_22_8_n_70));
  NOR2X2 mul_22_8_g1341(.A (mul_22_8_n_24), .B (mul_22_8_n_29), .Y
       (mul_22_8_n_69));
  NAND2X1 mul_22_8_g1342(.A (in1[2]), .B (in2[0]), .Y (mul_22_8_n_99));
  NAND2X1 mul_22_8_g1343(.A (in1[0]), .B (in2[1]), .Y (mul_22_8_n_98));
  NAND2X1 mul_22_8_g1344(.A (in1[2]), .B (in2[1]), .Y (mul_22_8_n_97));
  NAND2X1 mul_22_8_g1345(.A (in1[6]), .B (in2[0]), .Y (mul_22_8_n_96));
  NAND2X1 mul_22_8_g1346(.A (in1[5]), .B (in2[1]), .Y (mul_22_8_n_95));
  NAND2X1 mul_22_8_g1347(.A (in1[6]), .B (in2[1]), .Y (mul_22_8_n_94));
  AND2XL mul_22_8_g1348(.A (in1[1]), .B (in2[1]), .Y (mul_22_8_n_68));
  NAND2X1 mul_22_8_g1349(.A (in1[0]), .B (in2[2]), .Y (mul_22_8_n_93));
  NAND2X1 mul_22_8_g1350(.A (in1[1]), .B (in2[0]), .Y (mul_22_8_n_92));
  NAND2X4 mul_22_8_g1351(.A (in1[6]), .B (in2[2]), .Y (mul_22_8_n_91));
  NOR2X1 mul_22_8_g1352(.A (mul_22_8_n_22), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_59));
  NOR2X1 mul_22_8_g1353(.A (mul_22_8_n_21), .B (n_351), .Y
       (mul_22_8_n_58));
  NOR2X1 mul_22_8_g1354(.A (mul_22_8_n_24), .B (n_349), .Y
       (mul_22_8_n_57));
  NOR2X1 mul_22_8_g1355(.A (n_339), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_56));
  NOR2X1 mul_22_8_g1356(.A (mul_22_8_n_22), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_55));
  NOR2X1 mul_22_8_g1357(.A (n_332), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_54));
  NOR2X1 mul_22_8_g1358(.A (mul_22_8_n_33), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_53));
  NOR2X1 mul_22_8_g1359(.A (mul_22_8_n_24), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_52));
  NOR2X1 mul_22_8_g1360(.A (mul_22_8_n_33), .B (n_352), .Y
       (mul_22_8_n_51));
  NOR2X1 mul_22_8_g1361(.A (n_338), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_50));
  NOR2X1 mul_22_8_g1362(.A (mul_22_8_n_21), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_49));
  NOR2X1 mul_22_8_g1363(.A (n_343), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_48));
  NOR2X1 mul_22_8_g1364(.A (mul_22_8_n_23), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_47));
  NOR2X1 mul_22_8_g1365(.A (mul_22_8_n_28), .B (mul_22_8_n_23), .Y
       (mul_22_8_n_46));
  NOR2X1 mul_22_8_g1366(.A (mul_22_8_n_35), .B (n_350), .Y
       (mul_22_8_n_45));
  NOR2X1 mul_22_8_g1367(.A (mul_22_8_n_23), .B (n_351), .Y
       (mul_22_8_n_44));
  NOR2X1 mul_22_8_g1368(.A (n_332), .B (mul_22_8_n_30), .Y
       (mul_22_8_n_43));
  NOR2X1 mul_22_8_g1369(.A (n_333), .B (mul_22_8_n_29), .Y
       (mul_22_8_n_42));
  NOR2X1 mul_22_8_g1370(.A (mul_22_8_n_35), .B (mul_22_8_n_30), .Y
       (mul_22_8_n_41));
  NOR2X1 mul_22_8_g1371(.A (mul_22_8_n_35), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_40));
  NOR2X1 mul_22_8_g1372(.A (n_336), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_39));
  NOR2X1 mul_22_8_g1373(.A (mul_22_8_n_35), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_38));
  NOR2X1 mul_22_8_g1374(.A (n_333), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_37));
  NOR2X1 mul_22_8_g1375(.A (mul_22_8_n_33), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_36));
  NAND2X4 mul_22_8_g1376(.A (in1[7]), .B (in2[1]), .Y (mul_22_8_n_67));
  NAND2X1 mul_22_8_g1377(.A (n_341), .B (in2[1]), .Y (mul_22_8_n_66));
  NAND2X1 mul_22_8_g1378(.A (n_331), .B (in2[0]), .Y (mul_22_8_n_65));
  NAND2X1 mul_22_8_g1379(.A (in1[7]), .B (in2[7]), .Y (mul_22_8_n_64));
  NAND2X1 mul_22_8_g1380(.A (in1[3]), .B (in2[0]), .Y (mul_22_8_n_63));
  NAND2X2 mul_22_8_g1381(.A (in1[5]), .B (in2[0]), .Y (mul_22_8_n_62));
  NAND2X4 mul_22_8_g1382(.A (n_335), .B (in2[1]), .Y (mul_22_8_n_61));
  NAND2X1 mul_22_8_g1383(.A (in1[7]), .B (in2[0]), .Y (mul_22_8_n_60));
  CLKINVX12 mul_22_8_g1384(.A (in1[5]), .Y (mul_22_8_n_35));
  CLKINVX12 mul_22_8_g1386(.A (in1[2]), .Y (mul_22_8_n_33));
  CLKINVX16 mul_22_8_g1389(.A (in2[6]), .Y (mul_22_8_n_30));
  CLKINVX3 mul_22_8_g1390(.A (in2[7]), .Y (mul_22_8_n_29));
  CLKINVX3 mul_22_8_g1391(.A (in2[4]), .Y (mul_22_8_n_28));
  CLKINVX3 mul_22_8_g1392(.A (in2[4]), .Y (mul_22_8_n_27));
  INVX3 mul_22_8_g1393(.A (in2[2]), .Y (mul_22_8_n_26));
  INVX3 mul_22_8_g1394(.A (in2[5]), .Y (mul_22_8_n_25));
  INVX2 mul_22_8_g1395(.A (in1[0]), .Y (mul_22_8_n_24));
  CLKINVX2 mul_22_8_g1396(.A (in1[7]), .Y (mul_22_8_n_23));
  INVX2 mul_22_8_g1397(.A (in1[1]), .Y (mul_22_8_n_22));
  INVX1 mul_22_8_g1398(.A (in1[6]), .Y (mul_22_8_n_21));
  NOR2BX1 mul_22_8_g1399(.AN (mul_22_8_n_128), .B (mul_22_8_n_124), .Y
       (mul_22_8_n_20));
  NOR2X1 mul_22_8_g1400(.A (n_289), .B (mul_22_8_n_14), .Y
       (mul_22_8_n_19));
  NOR2X2 mul_22_8_g1401(.A (mul_22_8_n_10), .B (mul_22_8_n_181), .Y
       (mul_22_8_n_18));
  XNOR2X1 mul_22_8_g2(.A (mul_22_8_n_170), .B (mul_22_8_n_19), .Y
       (out1[10]));
  XNOR2X1 mul_22_8_g1402(.A (mul_22_8_n_12), .B (mul_22_8_n_175), .Y
       (out1[9]));
  XNOR2X1 mul_22_8_g1403(.A (mul_22_8_n_11), .B (n_303), .Y (out1[8]));
  NOR2BX1 mul_22_8_g1404(.AN (mul_22_8_n_168), .B (mul_22_8_n_155), .Y
       (mul_22_8_n_14));
  XNOR2X1 mul_22_8_g1405(.A (mul_22_8_n_167), .B (mul_22_8_n_18), .Y
       (out1[12]));
  NOR2BX1 mul_22_8_g1406(.AN (mul_22_8_n_164), .B (n_316), .Y
       (mul_22_8_n_12));
  NOR2BX1 mul_22_8_g1407(.AN (mul_22_8_n_161), .B (mul_22_8_n_156), .Y
       (mul_22_8_n_11));
  NOR2X2 mul_22_8_g1408(.A (mul_22_8_n_155), .B (mul_22_8_n_177), .Y
       (mul_22_8_n_10));
  AND2X1 mul_22_8_g1409(.A (mul_22_8_n_259), .B (mul_22_8_n_248), .Y
       (mul_22_8_n_9));
  CLKXOR2X1 mul_22_8_g1410(.A (mul_22_8_n_7), .B (mul_22_8_n_145), .Y
       (out1[7]));
  NOR2BX1 mul_22_8_g1411(.AN (mul_22_8_n_147), .B (mul_22_8_n_146), .Y
       (mul_22_8_n_7));
  NAND2BX1 mul_22_8_g1412(.AN (mul_22_8_n_139), .B (mul_22_8_n_140), .Y
       (mul_22_8_n_6));
  CLKXOR2X1 mul_22_8_g1413(.A (mul_22_8_n_4), .B (mul_22_8_n_6), .Y
       (out1[6]));
  AND2X1 mul_22_8_g1414(.A (mul_22_8_n_135), .B (mul_22_8_n_137), .Y
       (mul_22_8_n_4));
  XNOR2X1 mul_22_8_g1415(.A (mul_22_8_n_132), .B (mul_22_8_n_136), .Y
       (out1[5]));
  CLKXOR2X1 mul_22_8_g1416(.A (mul_22_8_n_128), .B (mul_22_8_n_129), .Y
       (out1[4]));
  NOR2BX1 mul_22_8_g1417(.AN (mul_22_8_n_0), .B (mul_22_8_n_133), .Y
       (mul_22_8_n_1));
  NOR2BX1 mul_22_8_g1418(.AN (mul_22_8_n_242), .B (mul_22_8_n_121), .Y
       (mul_22_8_n_0));
  BUFX2 fopt(.A (mul_22_8_n_10), .Y (n_287));
  BUFX2 fopt1425(.A (mul_22_8_n_176), .Y (n_289));
  INVXL fopt1426(.A (mul_22_8_n_260), .Y (n_291));
  CLKINVX1 fopt1427(.A (mul_22_8_n_260), .Y (n_292));
  BUFX2 fopt1428(.A (mul_22_8_n_181), .Y (n_294));
  BUFX3 fopt1433(.A (mul_22_8_n_103), .Y (n_301));
  INVXL fopt1434(.A (n_305), .Y (n_303));
  INVXL fopt1435(.A (n_305), .Y (n_304));
  INVXL fopt1436(.A (mul_22_8_n_155), .Y (n_305));
  BUFX2 fopt1444(.A (mul_22_8_n_160), .Y (n_316));
  INVXL fopt1452(.A (n_329), .Y (n_327));
  INVXL fopt1453(.A (n_329), .Y (n_328));
  INVXL fopt1454(.A (mul_22_8_n_162), .Y (n_329));
  INVXL fopt1455(.A (n_332), .Y (n_331));
  CLKINVX1 fopt1456(.A (in1[4]), .Y (n_332));
  CLKINVX1 fopt1457(.A (in1[4]), .Y (n_333));
  CLKINVX2 fopt1458(.A (n_336), .Y (n_335));
  CLKINVX6 fopt1459(.A (in1[4]), .Y (n_336));
  CLKINVX8 fopt1460(.A (in1[3]), .Y (n_337));
  CLKINVX1 fopt1461(.A (in1[3]), .Y (n_338));
  INVXL fopt1462(.A (in1[3]), .Y (n_339));
  INVXL fopt1463(.A (n_343), .Y (n_341));
  INVXL fopt1464(.A (n_343), .Y (n_342));
  CLKINVX1 fopt1465(.A (in1[3]), .Y (n_343));
  CLKINVX2 fopt1466(.A (in1[3]), .Y (n_344));
  CLKINVX2 fopt1467(.A (in2[3]), .Y (n_346));
  CLKINVX3 fopt1468(.A (in2[3]), .Y (n_347));
  BUFX2 fopt1469(.A (n_350), .Y (n_349));
  CLKINVX1 fopt1470(.A (in2[3]), .Y (n_350));
  CLKINVX1 fopt1471(.A (in2[3]), .Y (n_351));
  CLKINVX1 fopt1472(.A (in2[3]), .Y (n_352));
endmodule


