`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: Nov  1 2023 15:54:02 CST (Nov  1 2023 07:54:02 UTC)

module SysPE_Add_32Ux16U_32U_4(in2, in1, out1);
  input [31:0] in2;
  input [15:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [15:0] in1;
  wire [31:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23;
  wire add_23_2_n_24, add_23_2_n_25, add_23_2_n_26, add_23_2_n_27,
       add_23_2_n_28, add_23_2_n_29, add_23_2_n_30, add_23_2_n_31;
  wire add_23_2_n_32, add_23_2_n_33, add_23_2_n_34, add_23_2_n_35,
       add_23_2_n_36, add_23_2_n_37, add_23_2_n_38, add_23_2_n_39;
  wire add_23_2_n_40, add_23_2_n_41, add_23_2_n_42, add_23_2_n_43,
       add_23_2_n_44, add_23_2_n_45, add_23_2_n_46, add_23_2_n_47;
  wire add_23_2_n_48, add_23_2_n_49, add_23_2_n_50, add_23_2_n_51,
       add_23_2_n_52, add_23_2_n_53, add_23_2_n_54, add_23_2_n_55;
  wire add_23_2_n_56, add_23_2_n_57, add_23_2_n_58, add_23_2_n_59,
       add_23_2_n_60, add_23_2_n_61, add_23_2_n_63, add_23_2_n_64;
  wire add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68,
       add_23_2_n_69, add_23_2_n_71, add_23_2_n_72, add_23_2_n_73;
  wire add_23_2_n_74, add_23_2_n_76, add_23_2_n_79, add_23_2_n_80,
       add_23_2_n_81, add_23_2_n_82, add_23_2_n_86, add_23_2_n_87;
  wire add_23_2_n_88, add_23_2_n_89, add_23_2_n_90, add_23_2_n_91,
       add_23_2_n_92, add_23_2_n_93, add_23_2_n_94, add_23_2_n_95;
  wire add_23_2_n_101, add_23_2_n_102, add_23_2_n_103, add_23_2_n_104,
       add_23_2_n_105, add_23_2_n_106, add_23_2_n_110, add_23_2_n_111;
  wire add_23_2_n_112, add_23_2_n_113, add_23_2_n_118, add_23_2_n_119;
  XNOR2X1 add_23_2_g657(.A (in2[31]), .B (add_23_2_n_119), .Y
       (out1[31]));
  XNOR2X1 add_23_2_g658(.A (in2[23]), .B (add_23_2_n_112), .Y
       (out1[23]));
  XNOR2X1 add_23_2_g659(.A (in2[27]), .B (add_23_2_n_111), .Y
       (out1[27]));
  XNOR2X1 add_23_2_g660(.A (in2[29]), .B (add_23_2_n_113), .Y
       (out1[29]));
  XNOR2X1 add_23_2_g661(.A (in2[21]), .B (add_23_2_n_103), .Y
       (out1[21]));
  XNOR2X1 add_23_2_g662(.A (in2[19]), .B (add_23_2_n_102), .Y
       (out1[19]));
  XNOR2X1 add_23_2_g663(.A (add_23_2_n_39), .B (add_23_2_n_118), .Y
       (out1[15]));
  XNOR2X1 add_23_2_g664(.A (in2[25]), .B (add_23_2_n_101), .Y
       (out1[25]));
  XNOR2X1 add_23_2_g665(.A (in2[30]), .B (add_23_2_n_110), .Y
       (out1[30]));
  XNOR2X1 add_23_2_g666(.A (in2[17]), .B (add_23_2_n_1), .Y (out1[17]));
  XNOR2X1 add_23_2_g667(.A (in2[28]), .B (add_23_2_n_0), .Y (out1[28]));
  XNOR2X1 add_23_2_g668(.A (add_23_2_n_34), .B (add_23_2_n_105), .Y
       (out1[14]));
  NAND2BX1 add_23_2_g669(.AN (add_23_2_n_110), .B (in2[30]), .Y
       (add_23_2_n_119));
  OAI21X1 add_23_2_g670(.A0 (add_23_2_n_12), .A1 (add_23_2_n_105), .B0
       (add_23_2_n_18), .Y (add_23_2_n_118));
  XNOR2X1 add_23_2_g671(.A (in2[22]), .B (add_23_2_n_106), .Y
       (out1[22]));
  XNOR2X1 add_23_2_g672(.A (add_23_2_n_35), .B (add_23_2_n_94), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g673(.A (add_23_2_n_38), .B (add_23_2_n_95), .Y
       (out1[13]));
  XNOR2X1 add_23_2_g674(.A (in2[26]), .B (add_23_2_n_104), .Y
       (out1[26]));
  NAND2BX1 add_23_2_g675(.AN (add_23_2_n_0), .B (in2[28]), .Y
       (add_23_2_n_113));
  NAND2BX1 add_23_2_g676(.AN (add_23_2_n_106), .B (in2[22]), .Y
       (add_23_2_n_112));
  NAND2BX1 add_23_2_g677(.AN (add_23_2_n_104), .B (in2[26]), .Y
       (add_23_2_n_111));
  NAND3BXL add_23_2_g678(.AN (add_23_2_n_0), .B (in2[29]), .C
       (in2[28]), .Y (add_23_2_n_110));
  XOR2XL add_23_2_g679(.A (in2[24]), .B (add_23_2_n_91), .Y (out1[24]));
  XNOR2X1 add_23_2_g680(.A (in2[20]), .B (add_23_2_n_93), .Y
       (out1[20]));
  XNOR2X1 add_23_2_g681(.A (in2[18]), .B (add_23_2_n_92), .Y
       (out1[18]));
  NAND2BX1 add_23_2_g682(.AN (add_23_2_n_93), .B (in2[20]), .Y
       (add_23_2_n_103));
  NAND2BX1 add_23_2_g683(.AN (add_23_2_n_92), .B (in2[18]), .Y
       (add_23_2_n_102));
  NAND2X1 add_23_2_g684(.A (in2[24]), .B (add_23_2_n_91), .Y
       (add_23_2_n_101));
  OR2XL add_23_2_g685(.A (add_23_2_n_13), .B (add_23_2_n_93), .Y
       (add_23_2_n_106));
  AOI21X1 add_23_2_g686(.A0 (add_23_2_n_53), .A1 (add_23_2_n_90), .B0
       (add_23_2_n_56), .Y (add_23_2_n_105));
  NAND2BX1 add_23_2_g687(.AN (add_23_2_n_31), .B (add_23_2_n_91), .Y
       (add_23_2_n_104));
  XNOR2X1 add_23_2_g689(.A (in2[16]), .B (add_23_2_n_86), .Y
       (out1[16]));
  XNOR2X1 add_23_2_g690(.A (add_23_2_n_47), .B (add_23_2_n_87), .Y
       (out1[7]));
  XNOR2X1 add_23_2_g691(.A (add_23_2_n_37), .B (add_23_2_n_90), .Y
       (out1[12]));
  XNOR2X1 add_23_2_g692(.A (add_23_2_n_48), .B (add_23_2_n_89), .Y
       (out1[10]));
  XNOR2X1 add_23_2_g693(.A (add_23_2_n_36), .B (add_23_2_n_88), .Y
       (out1[9]));
  OAI2BB1X1 add_23_2_g694(.A0N (add_23_2_n_26), .A1N (add_23_2_n_90),
       .B0 (add_23_2_n_8), .Y (add_23_2_n_95));
  OAI21X1 add_23_2_g695(.A0 (add_23_2_n_11), .A1 (add_23_2_n_89), .B0
       (add_23_2_n_20), .Y (add_23_2_n_94));
  OR2XL add_23_2_g696(.A (add_23_2_n_40), .B (add_23_2_n_86), .Y
       (add_23_2_n_93));
  OR2XL add_23_2_g697(.A (add_23_2_n_29), .B (add_23_2_n_86), .Y
       (add_23_2_n_92));
  NOR4X1 add_23_2_g699(.A (add_23_2_n_86), .B (add_23_2_n_40), .C
       (add_23_2_n_2), .D (add_23_2_n_13), .Y (add_23_2_n_91));
  OAI211X1 add_23_2_g700(.A0 (add_23_2_n_60), .A1 (add_23_2_n_82), .B0
       (add_23_2_n_57), .C0 (add_23_2_n_66), .Y (add_23_2_n_90));
  AOI21X1 add_23_2_g701(.A0 (add_23_2_n_42), .A1 (add_23_2_n_81), .B0
       (add_23_2_n_58), .Y (add_23_2_n_89));
  OAI21X1 add_23_2_g702(.A0 (add_23_2_n_4), .A1 (add_23_2_n_82), .B0
       (add_23_2_n_21), .Y (add_23_2_n_88));
  OAI21X1 add_23_2_g703(.A0 (add_23_2_n_6), .A1 (add_23_2_n_79), .B0
       (add_23_2_n_19), .Y (add_23_2_n_87));
  AOI221X1 add_23_2_g705(.A0 (add_23_2_n_59), .A1 (add_23_2_n_67), .B0
       (add_23_2_n_65), .B1 (add_23_2_n_81), .C0 (add_23_2_n_69), .Y
       (add_23_2_n_86));
  XNOR2X1 add_23_2_g706(.A (add_23_2_n_46), .B (add_23_2_n_82), .Y
       (out1[8]));
  XNOR2X1 add_23_2_g707(.A (add_23_2_n_49), .B (add_23_2_n_79), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g708(.A (add_23_2_n_50), .B (add_23_2_n_80), .Y
       (out1[5]));
  INVX1 add_23_2_g709(.A (add_23_2_n_82), .Y (add_23_2_n_81));
  AOI31X1 add_23_2_g710(.A0 (add_23_2_n_73), .A1 (add_23_2_n_43), .A2
       (add_23_2_n_41), .B0 (add_23_2_n_68), .Y (add_23_2_n_82));
  OAI21X1 add_23_2_g711(.A0 (add_23_2_n_7), .A1 (add_23_2_n_74), .B0
       (add_23_2_n_23), .Y (add_23_2_n_80));
  AOI21X1 add_23_2_g712(.A0 (add_23_2_n_41), .A1 (add_23_2_n_73), .B0
       (add_23_2_n_55), .Y (add_23_2_n_79));
  XNOR2X1 add_23_2_g713(.A (add_23_2_n_52), .B (add_23_2_n_74), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g714(.A (add_23_2_n_51), .B (add_23_2_n_76), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g715(.A0N (add_23_2_n_5), .A1N (add_23_2_n_71),
       .B0 (add_23_2_n_27), .Y (add_23_2_n_76));
  XNOR2X1 add_23_2_g716(.A (add_23_2_n_45), .B (add_23_2_n_71), .Y
       (out1[2]));
  INVX1 add_23_2_g717(.A (add_23_2_n_73), .Y (add_23_2_n_74));
  OAI211X1 add_23_2_g718(.A0 (add_23_2_n_27), .A1 (add_23_2_n_22), .B0
       (add_23_2_n_72), .C0 (add_23_2_n_33), .Y (add_23_2_n_73));
  NAND3BXL add_23_2_g719(.AN (add_23_2_n_22), .B (add_23_2_n_71), .C
       (add_23_2_n_5), .Y (add_23_2_n_72));
  ADDFX1 add_23_2_g720(.A (add_23_2_n_61), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_71), .S (out1[1]));
  OAI211X1 add_23_2_g721(.A0 (add_23_2_n_18), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_64), .C0 (add_23_2_n_17), .Y (add_23_2_n_69));
  OAI211X1 add_23_2_g722(.A0 (add_23_2_n_19), .A1 (add_23_2_n_9), .B0
       (add_23_2_n_63), .C0 (add_23_2_n_16), .Y (add_23_2_n_68));
  NAND2X1 add_23_2_g723(.A (add_23_2_n_57), .B (add_23_2_n_66), .Y
       (add_23_2_n_67));
  NAND2X1 add_23_2_g724(.A (add_23_2_n_54), .B (add_23_2_n_58), .Y
       (add_23_2_n_66));
  NOR2BX1 add_23_2_g725(.AN (add_23_2_n_59), .B (add_23_2_n_60), .Y
       (add_23_2_n_65));
  NAND2X1 add_23_2_g726(.A (add_23_2_n_44), .B (add_23_2_n_56), .Y
       (add_23_2_n_64));
  NAND2X1 add_23_2_g727(.A (add_23_2_n_43), .B (add_23_2_n_55), .Y
       (add_23_2_n_63));
  ADDHX1 add_23_2_g728(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_61),
       .S (out1[0]));
  NAND2X1 add_23_2_g729(.A (add_23_2_n_54), .B (add_23_2_n_42), .Y
       (add_23_2_n_60));
  AND2XL add_23_2_g730(.A (add_23_2_n_44), .B (add_23_2_n_53), .Y
       (add_23_2_n_59));
  OAI21X1 add_23_2_g731(.A0 (add_23_2_n_21), .A1 (add_23_2_n_24), .B0
       (add_23_2_n_32), .Y (add_23_2_n_58));
  OA21X1 add_23_2_g732(.A0 (add_23_2_n_20), .A1 (add_23_2_n_3), .B0
       (add_23_2_n_30), .Y (add_23_2_n_57));
  OAI21X1 add_23_2_g733(.A0 (add_23_2_n_8), .A1 (add_23_2_n_10), .B0
       (add_23_2_n_14), .Y (add_23_2_n_56));
  OAI21X1 add_23_2_g734(.A0 (add_23_2_n_23), .A1 (add_23_2_n_25), .B0
       (add_23_2_n_15), .Y (add_23_2_n_55));
  NOR2BX1 add_23_2_g735(.AN (add_23_2_n_23), .B (add_23_2_n_7), .Y
       (add_23_2_n_52));
  NAND2BX1 add_23_2_g736(.AN (add_23_2_n_22), .B (add_23_2_n_33), .Y
       (add_23_2_n_51));
  NAND2BX1 add_23_2_g737(.AN (add_23_2_n_25), .B (add_23_2_n_15), .Y
       (add_23_2_n_50));
  NOR2BX1 add_23_2_g738(.AN (add_23_2_n_19), .B (add_23_2_n_6), .Y
       (add_23_2_n_49));
  NOR2X1 add_23_2_g739(.A (add_23_2_n_3), .B (add_23_2_n_11), .Y
       (add_23_2_n_54));
  NOR2BX1 add_23_2_g740(.AN (add_23_2_n_20), .B (add_23_2_n_11), .Y
       (add_23_2_n_48));
  NAND2BX1 add_23_2_g741(.AN (add_23_2_n_9), .B (add_23_2_n_16), .Y
       (add_23_2_n_47));
  NOR2BX1 add_23_2_g742(.AN (add_23_2_n_21), .B (add_23_2_n_4), .Y
       (add_23_2_n_46));
  NAND2X1 add_23_2_g743(.A (add_23_2_n_27), .B (add_23_2_n_5), .Y
       (add_23_2_n_45));
  NOR2BX1 add_23_2_g744(.AN (add_23_2_n_26), .B (add_23_2_n_10), .Y
       (add_23_2_n_53));
  NAND2BX1 add_23_2_g745(.AN (add_23_2_n_28), .B (add_23_2_n_17), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g746(.AN (add_23_2_n_10), .B (add_23_2_n_14), .Y
       (add_23_2_n_38));
  NOR2X1 add_23_2_g747(.A (add_23_2_n_28), .B (add_23_2_n_12), .Y
       (add_23_2_n_44));
  NAND2X1 add_23_2_g748(.A (add_23_2_n_8), .B (add_23_2_n_26), .Y
       (add_23_2_n_37));
  NOR2X1 add_23_2_g749(.A (add_23_2_n_9), .B (add_23_2_n_6), .Y
       (add_23_2_n_43));
  NOR2X1 add_23_2_g750(.A (add_23_2_n_24), .B (add_23_2_n_4), .Y
       (add_23_2_n_42));
  NAND2BX1 add_23_2_g751(.AN (add_23_2_n_24), .B (add_23_2_n_32), .Y
       (add_23_2_n_36));
  NAND2BX1 add_23_2_g752(.AN (add_23_2_n_3), .B (add_23_2_n_30), .Y
       (add_23_2_n_35));
  NOR2X1 add_23_2_g753(.A (add_23_2_n_25), .B (add_23_2_n_7), .Y
       (add_23_2_n_41));
  NOR2BX1 add_23_2_g754(.AN (add_23_2_n_18), .B (add_23_2_n_12), .Y
       (add_23_2_n_34));
  NAND3BXL add_23_2_g755(.AN (add_23_2_n_29), .B (in2[19]), .C
       (in2[18]), .Y (add_23_2_n_40));
  NAND2X1 add_23_2_g757(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_33));
  NAND2X1 add_23_2_g758(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_32));
  NAND2X1 add_23_2_g759(.A (in2[25]), .B (in2[24]), .Y (add_23_2_n_31));
  NAND2X1 add_23_2_g760(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_30));
  NAND2X1 add_23_2_g761(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_29));
  NOR2X1 add_23_2_g762(.A (in2[15]), .B (in1[15]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g763(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_27));
  OR2X1 add_23_2_g764(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_26));
  NOR2X1 add_23_2_g765(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_25));
  NOR2X1 add_23_2_g766(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_24));
  NAND2X1 add_23_2_g767(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_23));
  NOR2X1 add_23_2_g768(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_22));
  NAND2X1 add_23_2_g769(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g770(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_20));
  NAND2X1 add_23_2_g771(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_19));
  NAND2X1 add_23_2_g772(.A (in2[14]), .B (in1[14]), .Y (add_23_2_n_18));
  NAND2X1 add_23_2_g773(.A (in2[23]), .B (in2[22]), .Y (add_23_2_n_2));
  NAND2X1 add_23_2_g774(.A (in2[15]), .B (in1[15]), .Y (add_23_2_n_17));
  NAND2X1 add_23_2_g775(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_16));
  NAND2X1 add_23_2_g776(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g777(.A (in2[13]), .B (in1[13]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g778(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_13));
  NOR2X1 add_23_2_g779(.A (in2[14]), .B (in1[14]), .Y (add_23_2_n_12));
  NOR2X1 add_23_2_g780(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_11));
  NOR2X1 add_23_2_g781(.A (in2[13]), .B (in1[13]), .Y (add_23_2_n_10));
  NOR2X1 add_23_2_g782(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_9));
  NAND2X1 add_23_2_g783(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_8));
  NOR2X1 add_23_2_g784(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_7));
  NOR2X1 add_23_2_g785(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_6));
  OR2X1 add_23_2_g786(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g787(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g788(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_3));
  NAND2BX1 add_23_2_g2(.AN (add_23_2_n_86), .B (in2[16]), .Y
       (add_23_2_n_1));
  NAND4BX1 add_23_2_g789(.AN (add_23_2_n_31), .B (add_23_2_n_91), .C
       (in2[27]), .D (in2[26]), .Y (add_23_2_n_0));
endmodule


