`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: Nov  1 2023 15:54:12 CST (Nov  1 2023 07:54:12 UTC)

module SysPE_Add_3U_11_4(in1, out1);
  input [2:0] in1;
  output [2:0] out1;
  wire [2:0] in1;
  wire [2:0] out1;
  wire inc_add_21_2_1_n_0;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_21_2_1_g19(.A (in1[2]), .B (inc_add_21_2_1_n_0), .Y
       (out1[2]));
  XOR2XL inc_add_21_2_1_g20(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_21_2_1_g21(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_21_2_1_n_0));
endmodule


