`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: Nov  1 2023 15:54:03 CST (Nov  1 2023 07:54:03 UTC)

module SysPE_Or_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  OR2XL g2(.A (in2), .B (in1), .Y (out1));
endmodule


